
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package br.compiler.syntacticanalyzer;

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\111\000\002\002\004\000\002\002\003\000\002\003" +
    "\006\000\002\003\006\000\002\004\006\000\002\005\003" +
    "\000\002\005\003\000\002\006\003\000\002\006\003\000" +
    "\002\007\003\000\002\007\003\000\002\010\005\000\002" +
    "\011\004\000\002\012\007\000\002\012\006\000\002\013" +
    "\004\000\002\014\004\000\002\014\003\000\002\015\005" +
    "\000\002\016\004\000\002\016\003\000\002\017\003\000" +
    "\002\020\006\000\002\020\004\000\002\021\005\000\002" +
    "\021\003\000\002\022\003\000\002\023\006\000\002\023" +
    "\005\000\002\024\005\000\002\024\003\000\002\024\003" +
    "\000\002\025\003\000\002\025\003\000\002\025\003\000" +
    "\002\025\003\000\002\025\003\000\002\025\003\000\002" +
    "\025\003\000\002\026\006\000\002\027\004\000\002\030" +
    "\005\000\002\031\005\000\002\031\004\000\002\032\005" +
    "\000\002\033\004\000\002\033\003\000\002\034\007\000" +
    "\002\034\011\000\002\035\007\000\002\036\003\000\002" +
    "\036\005\000\002\037\004\000\002\037\005\000\002\040" +
    "\005\000\002\040\003\000\002\041\004\000\002\042\005" +
    "\000\002\042\003\000\002\043\003\000\002\043\003\000" +
    "\002\043\003\000\002\043\005\000\002\043\004\000\002" +
    "\044\006\000\002\045\004\000\002\046\005\000\002\046" +
    "\003\000\002\047\004\000\002\047\003\000\002\050\005" +
    "\000\002\050\003\000\002\051\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\220\000\006\014\006\031\007\001\002\000\004\002" +
    "\000\001\002\000\004\002\222\001\002\000\004\014\217" +
    "\001\002\000\004\014\010\001\002\000\004\021\012\001" +
    "\002\000\012\017\uffb9\025\uffb9\026\uffb9\027\043\001\002" +
    "\000\010\014\017\020\015\030\014\001\002\000\006\007" +
    "\uffe7\020\uffe7\001\002\000\004\014\017\001\002\000\012" +
    "\017\uffea\025\uffea\026\uffea\027\uffea\001\002\000\004\006" +
    "\034\001\002\000\010\006\uffb9\007\uffb9\015\027\001\002" +
    "\000\006\007\022\020\uffb9\001\002\000\004\020\026\001" +
    "\002\000\006\014\017\030\014\001\002\000\004\020\uffe8" +
    "\001\002\000\006\007\022\020\uffb9\001\002\000\004\020" +
    "\uffe9\001\002\000\012\017\uffeb\025\uffeb\026\uffeb\027\uffeb" +
    "\001\002\000\004\014\032\001\002\000\006\006\uffc0\007" +
    "\uffc0\001\002\000\006\006\uffbe\007\uffbe\001\002\000\010" +
    "\006\uffb9\007\uffb9\015\027\001\002\000\006\006\uffbf\007" +
    "\uffbf\001\002\000\004\014\035\001\002\000\006\007\uffe5" +
    "\020\uffe5\001\002\000\004\006\037\001\002\000\004\014" +
    "\040\001\002\000\006\007\uffe6\020\uffe6\001\002\000\010" +
    "\017\uffb9\025\uffb9\026\050\001\002\000\010\017\ufffb\025" +
    "\ufffb\026\ufffb\001\002\000\004\014\017\001\002\000\012" +
    "\002\ufffe\014\ufffe\017\ufffe\031\ufffe\001\002\000\010\017" +
    "\ufffc\025\ufffc\026\ufffc\001\002\000\004\007\047\001\002" +
    "\000\010\017\ufff6\025\ufff6\026\ufff6\001\002\000\004\014" +
    "\017\001\002\000\006\017\uffb9\025\055\001\002\000\006" +
    "\017\ufff9\025\ufff9\001\002\000\006\017\ufffa\025\ufffa\001" +
    "\002\000\004\017\063\001\002\000\006\014\006\031\007" +
    "\001\002\000\004\017\ufff7\001\002\000\004\017\ufff8\001" +
    "\002\000\010\014\006\017\ufff0\031\007\001\002\000\004" +
    "\017\ufff2\001\002\000\004\017\ufff1\001\002\000\022\007" +
    "\105\014\073\016\uffb9\017\075\022\076\024\071\032\070" +
    "\033\072\001\002\000\012\002\ufffd\014\ufffd\017\ufffd\031" +
    "\ufffd\001\002\000\022\007\uffe0\014\uffe0\016\uffe0\017\uffe0" +
    "\022\uffe0\024\uffe0\032\uffe0\033\uffe0\001\002\000\022\007" +
    "\uffdc\014\uffdc\016\uffdc\017\uffdc\022\uffdc\024\uffdc\032\uffdc" +
    "\033\uffdc\001\002\000\022\007\105\014\073\016\uffb9\017" +
    "\075\022\076\024\071\032\070\033\072\001\002\000\004" +
    "\014\205\001\002\000\004\021\201\001\002\000\016\004" +
    "\123\007\176\011\113\013\122\014\121\021\112\001\002" +
    "\000\010\005\167\006\174\021\133\001\002\000\004\007" +
    "\173\001\002\000\016\007\105\014\164\022\076\024\071" +
    "\032\070\033\072\001\002\000\004\021\111\001\002\000" +
    "\004\016\uffed\001\002\000\022\007\uffe3\014\uffe3\016\uffe3" +
    "\017\uffe3\022\uffe3\024\uffe3\032\uffe3\033\uffe3\001\002\000" +
    "\004\016\110\001\002\000\022\007\uffe1\014\uffe1\016\uffe1" +
    "\017\uffe1\022\uffe1\024\uffe1\032\uffe1\033\uffe1\001\002\000" +
    "\022\007\uffdd\014\uffdd\016\uffdd\017\uffdd\022\uffdd\024\uffdd" +
    "\032\uffdd\033\uffdd\001\002\000\022\007\uffde\014\uffde\016" +
    "\uffde\017\uffde\022\uffde\024\uffde\032\uffde\033\uffde\001\002" +
    "\000\022\007\uffdb\014\uffdb\016\uffdb\017\uffdb\022\uffdb\024" +
    "\uffdb\032\uffdb\033\uffdb\001\002\000\022\007\uffe2\014\uffe2" +
    "\016\uffe2\017\uffe2\022\uffe2\024\uffe2\032\uffe2\033\uffe2\001" +
    "\002\000\022\007\uffdf\014\uffdf\016\uffdf\017\uffdf\022\uffdf" +
    "\024\uffdf\032\uffdf\033\uffdf\001\002\000\012\002\uffef\014" +
    "\uffef\017\uffef\031\uffef\001\002\000\014\004\123\011\113" +
    "\013\122\014\121\021\112\001\002\000\014\004\123\011" +
    "\113\013\122\014\121\021\112\001\002\000\016\007\uffc5" +
    "\010\uffc5\012\uffc5\013\uffc5\015\uffc5\020\uffc5\001\002\000" +
    "\014\007\uffb9\010\uffb9\013\127\015\uffb9\020\uffb9\001\002" +
    "\000\016\007\uffc4\010\uffc4\012\uffc4\013\uffc4\015\uffc4\020" +
    "\uffc4\001\002\000\004\020\154\001\002\000\012\007\uffcf" +
    "\010\152\015\uffcf\020\uffcf\001\002\000\016\007\uffb9\010" +
    "\uffb9\012\145\013\uffb9\015\uffb9\020\uffb9\001\002\000\020" +
    "\007\uffc6\010\uffc6\012\uffc6\013\uffc6\015\uffc6\020\uffc6\021" +
    "\133\001\002\000\012\004\123\011\113\014\121\021\112" +
    "\001\002\000\012\004\123\011\113\014\121\021\112\001" +
    "\002\000\016\007\uffc2\010\uffc2\012\uffc2\013\uffc2\015\uffc2" +
    "\020\uffc2\001\002\000\014\007\uffb9\010\uffb9\013\127\015" +
    "\uffb9\020\uffb9\001\002\000\012\007\uffcc\010\uffcc\015\uffcc" +
    "\020\uffcc\001\002\000\012\004\123\011\113\014\121\021" +
    "\112\001\002\000\012\007\uffca\010\uffca\015\uffca\020\uffca" +
    "\001\002\000\014\007\uffb9\010\uffb9\013\127\015\uffb9\020" +
    "\uffb9\001\002\000\012\007\uffcb\010\uffcb\015\uffcb\020\uffcb" +
    "\001\002\000\016\004\123\011\113\013\122\014\121\020" +
    "\uffb9\021\112\001\002\000\004\020\uffbc\001\002\000\006" +
    "\015\140\020\uffb9\001\002\000\004\020\137\001\002\000" +
    "\016\007\uffc1\010\uffc1\012\uffc1\013\uffc1\015\uffc1\020\uffc1" +
    "\001\002\000\014\004\123\011\113\013\122\014\121\021" +
    "\112\001\002\000\004\020\uffbd\001\002\000\004\020\uffba" +
    "\001\002\000\006\015\140\020\uffb9\001\002\000\004\020" +
    "\uffbb\001\002\000\012\004\123\011\113\014\121\021\112" +
    "\001\002\000\014\007\uffc7\010\uffc7\013\uffc7\015\uffc7\020" +
    "\uffc7\001\002\000\014\007\uffc9\010\uffc9\013\uffc9\015\uffc9" +
    "\020\uffc9\001\002\000\016\007\uffb9\010\uffb9\012\145\013" +
    "\uffb9\015\uffb9\020\uffb9\001\002\000\014\007\uffc8\010\uffc8" +
    "\013\uffc8\015\uffc8\020\uffc8\001\002\000\014\004\123\011" +
    "\113\013\122\014\121\021\112\001\002\000\010\007\uffce" +
    "\015\uffce\020\uffce\001\002\000\004\017\075\001\002\000" +
    "\024\007\uffd2\014\uffd2\016\uffd2\017\uffd2\022\uffd2\023\156" +
    "\024\uffd2\032\uffd2\033\uffd2\001\002\000\004\017\075\001" +
    "\002\000\022\007\uffd1\014\uffd1\016\uffd1\017\uffd1\022\uffd1" +
    "\024\uffd1\032\uffd1\033\uffd1\001\002\000\012\007\uffcd\010" +
    "\uffcd\015\uffcd\020\uffcd\001\002\000\004\020\162\001\002" +
    "\000\016\007\uffc3\010\uffc3\012\uffc3\013\uffc3\015\uffc3\020" +
    "\uffc3\001\002\000\004\016\172\001\002\000\006\005\167" +
    "\021\133\001\002\000\020\007\105\014\164\016\uffd3\022" +
    "\076\024\071\032\070\033\072\001\002\000\004\016\uffd4" +
    "\001\002\000\014\004\123\011\113\013\122\014\121\021" +
    "\112\001\002\000\004\007\171\001\002\000\022\007\uffda" +
    "\014\uffda\016\uffda\017\uffda\022\uffda\024\uffda\032\uffda\033" +
    "\uffda\001\002\000\024\007\uffd5\014\uffd5\016\uffd5\017\uffd5" +
    "\022\uffd5\023\uffd5\024\uffd5\032\uffd5\033\uffd5\001\002\000" +
    "\022\007\uffd9\014\uffd9\016\uffd9\017\uffd9\022\uffd9\024\uffd9" +
    "\032\uffd9\033\uffd9\001\002\000\016\007\105\014\164\022" +
    "\076\024\071\032\070\033\072\001\002\000\022\007\uffe4" +
    "\014\uffe4\016\uffe4\017\uffe4\022\uffe4\024\uffe4\032\uffe4\033" +
    "\uffe4\001\002\000\022\007\uffd6\014\uffd6\016\uffd6\017\uffd6" +
    "\022\uffd6\024\uffd6\032\uffd6\033\uffd6\001\002\000\004\007" +
    "\200\001\002\000\022\007\uffd7\014\uffd7\016\uffd7\017\uffd7" +
    "\022\uffd7\024\uffd7\032\uffd7\033\uffd7\001\002\000\014\004" +
    "\123\011\113\013\122\014\121\021\112\001\002\000\004" +
    "\020\203\001\002\000\004\017\075\001\002\000\022\007" +
    "\uffd0\014\uffd0\016\uffd0\017\uffd0\022\uffd0\024\uffd0\032\uffd0" +
    "\033\uffd0\001\002\000\004\007\206\001\002\000\022\007" +
    "\uffd8\014\uffd8\016\uffd8\017\uffd8\022\uffd8\024\uffd8\032\uffd8" +
    "\033\uffd8\001\002\000\004\016\uffee\001\002\000\006\017" +
    "\ufff5\025\ufff5\001\002\000\004\006\212\001\002\000\004" +
    "\014\214\001\002\000\004\007\215\001\002\000\004\007" +
    "\uffec\001\002\000\010\014\017\017\ufff3\025\ufff3\001\002" +
    "\000\006\017\ufff4\025\ufff4\001\002\000\004\021\012\001" +
    "\002\000\012\017\uffb9\025\uffb9\026\uffb9\027\043\001\002" +
    "\000\012\002\uffff\014\uffff\017\uffff\031\uffff\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\220\000\006\002\004\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\020\010\001\001\000\012\004\043\005\040\010" +
    "\044\051\041\001\001\000\010\022\017\023\012\045\015" +
    "\001\001\000\002\001\001\000\004\045\035\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\046\027\051\030" +
    "\001\001\000\006\021\020\051\022\001\001\000\002\001" +
    "\001\000\010\022\023\023\012\045\015\001\001\000\002" +
    "\001\001\000\006\021\024\051\022\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\046\032\051\030\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\006" +
    "\050\011\052\051\051\001\001\000\002\001\001\000\004" +
    "\045\045\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\012\207\045\210" +
    "\001\001\000\010\007\053\013\056\051\055\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\015\063\001\001" +
    "\000\006\003\057\014\060\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\003\057\014\061\001\001\000\002" +
    "\001\001\000\002\001\001\000\032\016\100\024\066\025" +
    "\077\026\101\027\064\030\106\031\103\032\105\034\102" +
    "\035\065\044\073\051\076\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\032\016\206\024\066" +
    "\025\077\026\101\027\064\030\106\031\103\032\105\034" +
    "\102\035\065\044\073\051\076\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\036\176\037\116\041\113\043" +
    "\117\044\114\001\001\000\002\001\001\000\002\001\001" +
    "\000\024\025\164\026\101\027\064\030\106\031\103\033" +
    "\162\034\102\035\065\044\073\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\036\115\037\116\041\113\043\117\044\114" +
    "\001\001\000\014\036\160\037\116\041\113\043\117\044" +
    "\114\001\001\000\002\001\001\000\006\040\157\051\127" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\042\146\051\145\001\001\000\002\001\001" +
    "\000\010\041\124\043\117\044\114\001\001\000\006\043" +
    "\123\044\114\001\001\000\002\001\001\000\006\040\125" +
    "\051\127\001\001\000\002\001\001\000\010\041\130\043" +
    "\117\044\114\001\001\000\002\001\001\000\006\040\131" +
    "\051\127\001\001\000\002\001\001\000\020\036\134\037" +
    "\116\041\113\043\117\044\114\047\135\051\133\001\001" +
    "\000\002\001\001\000\006\050\140\051\141\001\001\000" +
    "\002\001\001\000\002\001\001\000\014\036\142\037\116" +
    "\041\113\043\117\044\114\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\050\143\051\141\001\001\000\002" +
    "\001\001\000\006\043\147\044\114\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\042\150\051\145\001\001" +
    "\000\002\001\001\000\012\037\152\041\113\043\117\044" +
    "\114\001\001\000\002\001\001\000\004\032\154\001\001" +
    "\000\002\001\001\000\004\032\156\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\024\025\164\026" +
    "\101\027\064\030\106\031\103\033\165\034\102\035\065" +
    "\044\073\001\001\000\002\001\001\000\014\036\167\037" +
    "\116\041\113\043\117\044\114\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\022\025\174\026\101\027\064\030\106\031\103\034\102" +
    "\035\065\044\073\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\036\201" +
    "\037\116\041\113\043\117\044\114\001\001\000\002\001" +
    "\001\000\004\032\203\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\017\212\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\012\215\045\210\001" +
    "\001\000\002\001\001\000\004\020\217\001\001\000\012" +
    "\004\220\005\040\010\044\051\041\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    System.out.println("Starting syntactic analysis...");

    }



    public void report_error(String message, Object info)  {
        System.out.println("Warning - " + message + " " + info);
    }

    public void report_fatal_error(String message, Object info)  {
        System.out.println("Error - " + message + " " + info);
        //System.exit(-1);
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= function 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // function ::= IDENTIFIER IDENTIFIER formal_parameters block 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // function ::= VOID IDENTIFIER formal_parameters block 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // block ::= block_aux_1 block_aux_2 block_aux_3 body 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("block",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // block_aux_1 ::= labels 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("block_aux_1",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // block_aux_1 ::= empty 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("block_aux_1",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // block_aux_2 ::= variables 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("block_aux_2",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // block_aux_2 ::= empty 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("block_aux_2",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // block_aux_3 ::= functions 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("block_aux_3",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // block_aux_3 ::= empty 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("block_aux_3",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // labels ::= LABELS identifier_list EMPTYSTATEMENT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("labels",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // variables ::= VARS id_list_type_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("variables",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // id_list_type_aux ::= identifier_list COLON type EMPTYSTATEMENT id_list_type_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("id_list_type_aux",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // id_list_type_aux ::= identifier_list COLON type EMPTYSTATEMENT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("id_list_type_aux",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // functions ::= FUNCTIONS function_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("functions",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // function_aux ::= function function_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_aux",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // function_aux ::= function 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_aux",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // body ::= CURLYBRACESL statement_aux CURLYBRACESR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("body",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // statement_aux ::= statement statement_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_aux",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // statement_aux ::= empty 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_aux",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // type ::= IDENTIFIER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // formal_parameters ::= PARENTHESESL formal_parameter fp_aux PARENTHESESR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("formal_parameters",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // formal_parameters ::= PARENTHESESL PARENTHESESR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("formal_parameters",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // fp_aux ::= EMPTYSTATEMENT formal_parameter fp_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fp_aux",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // fp_aux ::= empty 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fp_aux",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // formal_parameter ::= expression_parameter 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("formal_parameter",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expression_parameter ::= VAR identifier_list COLON IDENTIFIER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression_parameter",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expression_parameter ::= identifier_list COLON IDENTIFIER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression_parameter",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // statement ::= IDENTIFIER COLON unlabeled_statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // statement ::= unlabeled_statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // statement ::= compound 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // unlabeled_statement ::= assignment 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("unlabeled_statement",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // unlabeled_statement ::= function_call_statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("unlabeled_statement",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // unlabeled_statement ::= goto 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("unlabeled_statement",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // unlabeled_statement ::= return 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("unlabeled_statement",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // unlabeled_statement ::= conditional 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("unlabeled_statement",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // unlabeled_statement ::= repetitive 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("unlabeled_statement",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // unlabeled_statement ::= EMPTYSTATEMENT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("unlabeled_statement",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // assignment ::= IDENTIFIER ASSIGNMENTOPERATOR expression EMPTYSTATEMENT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assignment",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // function_call_statement ::= function_call EMPTYSTATEMENT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_call_statement",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // goto ::= GOTO IDENTIFIER EMPTYSTATEMENT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("goto",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // return ::= RETURN expression EMPTYSTATEMENT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("return",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // return ::= RETURN EMPTYSTATEMENT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("return",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // compound ::= CURLYBRACESL unlabeled_statement_aux CURLYBRACESR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("compound",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // unlabeled_statement_aux ::= unlabeled_statement unlabeled_statement_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("unlabeled_statement_aux",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // unlabeled_statement_aux ::= unlabeled_statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("unlabeled_statement_aux",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // conditional ::= IF PARENTHESESL expression PARENTHESESR compound 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("conditional",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // conditional ::= IF PARENTHESESL expression PARENTHESESR compound ELSE compound 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("conditional",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // repetitive ::= WHILE PARENTHESESL expression PARENTHESESR compound 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("repetitive",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expression ::= simple_expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expression ::= simple_expression RELATIONALOPERATOR simple_expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // simple_expression ::= term add_op_term_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("simple_expression",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // simple_expression ::= ADDITIVEOPERATOR term add_op_term_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("simple_expression",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // add_op_term_aux ::= ADDITIVEOPERATOR term add_op_term_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("add_op_term_aux",30, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // add_op_term_aux ::= empty 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("add_op_term_aux",30, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // term ::= factor mul_op_factor_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",31, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // mul_op_factor_aux ::= MULTIPLICATIVEOPERATOR factor mul_op_factor_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mul_op_factor_aux",32, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // mul_op_factor_aux ::= empty 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mul_op_factor_aux",32, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // factor ::= IDENTIFIER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",33, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // factor ::= INTEGER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",33, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // factor ::= function_call 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",33, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // factor ::= PARENTHESESL expression PARENTHESESR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",33, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // factor ::= EXCLAMATIONMARK factor 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",33, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // function_call ::= IDENTIFIER PARENTHESESL expression_list PARENTHESESR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("function_call",34, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // identifier_list ::= IDENTIFIER id_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("identifier_list",35, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // id_aux ::= COMMA IDENTIFIER id_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("id_aux",36, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // id_aux ::= empty 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("id_aux",36, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expression_list ::= expression expression_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression_list",37, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expression_list ::= empty 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression_list",37, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expression_aux ::= COMMA expression expression_aux 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression_aux",38, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expression_aux ::= empty 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression_aux",38, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // empty ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("empty",39, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
