
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package br.compiler.syntacticanalyzer;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int MULTIPLICATIVEOPERATOR = 8;
  public static final int EXCLAMATIONMARK = 2;
  public static final int CURLYBRACESR = 16;
  public static final int IDENTIFIER = 10;
  public static final int ALTERNATIVE = 20;
  public static final int CURLYBRACESL = 17;
  public static final int QUOTATIONMARKS = 13;
  public static final int COLON = 4;
  public static final int ADDITIVEOPERATOR = 9;
  public static final int BRACKETR = 14;
  public static final int KEYWORD = 11;
  public static final int COMMA = 12;
  public static final int EOF = 0;
  public static final int BRACKETL = 15;
  public static final int error = 1;
  public static final int RELATIONALOPERATOR = 6;
  public static final int ASSIGNMENTOPERATOR = 3;
  public static final int EMPTYSTATEMENT = 5;
  public static final int PARENTHESESR = 18;
  public static final int INTEGER = 7;
  public static final int PARENTHESESL = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXCLAMATIONMARK",
  "ASSIGNMENTOPERATOR",
  "COLON",
  "EMPTYSTATEMENT",
  "RELATIONALOPERATOR",
  "INTEGER",
  "MULTIPLICATIVEOPERATOR",
  "ADDITIVEOPERATOR",
  "IDENTIFIER",
  "KEYWORD",
  "COMMA",
  "QUOTATIONMARKS",
  "BRACKETR",
  "BRACKETL",
  "CURLYBRACESR",
  "CURLYBRACESL",
  "PARENTHESESR",
  "PARENTHESESL",
  "ALTERNATIVE"
  };
}

