
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package br.compiler.syntacticanalyzer;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int MULTIPLICATIVEOPERATOR = 8;
  public static final int EXCLAMATIONMARK = 2;
  public static final int GOTO = 24;
  public static final int WHILE = 18;
  public static final int CURLYBRACESR = 13;
  public static final int RETURN = 25;
  public static final int IDENTIFIER = 10;
  public static final int ALTERNATIVE = 29;
  public static final int CURLYBRACESL = 14;
  public static final int QUOTATIONMARKS = 28;
  public static final int LABELS = 21;
  public static final int IF = 17;
  public static final int COLON = 4;
  public static final int ADDITIVEOPERATOR = 9;
  public static final int BRACKETR = 27;
  public static final int KEYWORD = 11;
  public static final int COMMA = 12;
  public static final int EOF = 0;
  public static final int BRACKETL = 26;
  public static final int error = 1;
  public static final int RELATIONALOPERATOR = 6;
  public static final int ASSIGNMENTOPERATOR = 3;
  public static final int FUNCTIONS = 19;
  public static final int EMPTYSTATEMENT = 5;
  public static final int PARENTHESESR = 15;
  public static final int INTEGER = 7;
  public static final int VOID = 23;
  public static final int VARS = 20;
  public static final int PARENTHESESL = 16;
  public static final int VAR = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXCLAMATIONMARK",
  "ASSIGNMENTOPERATOR",
  "COLON",
  "EMPTYSTATEMENT",
  "RELATIONALOPERATOR",
  "INTEGER",
  "MULTIPLICATIVEOPERATOR",
  "ADDITIVEOPERATOR",
  "IDENTIFIER",
  "KEYWORD",
  "COMMA",
  "CURLYBRACESR",
  "CURLYBRACESL",
  "PARENTHESESR",
  "PARENTHESESL",
  "IF",
  "WHILE",
  "FUNCTIONS",
  "VARS",
  "LABELS",
  "VAR",
  "VOID",
  "GOTO",
  "RETURN",
  "BRACKETL",
  "BRACKETR",
  "QUOTATIONMARKS",
  "ALTERNATIVE"
  };
}

